name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  create:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t anaskad01/library:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push anaskad01/library:${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: >
      github.ref_type == 'tag' ||
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/develop'


    environment: ${{ github.ref_type == 'tag' || github.ref == 'refs/heads/master' && 'Production' || 'Development' }}

    steps:
      - name: Select correct Render hook
        id: hooks
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" || "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Deploy BACK on Render
        run: |
          if [ "${{ steps.hooks.outputs.env }}" = "prod" ]; then
            echo "Deploying BACK to PROD..."
            curl -X POST "${{ secrets.RENDER_PROD_HOOK_BACK }}"
          else
            echo "Deploying BACK to DEV..."
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACK }}"
          fi

      - name: Deploy FRONT on Render
        run: |
          if [ "${{ steps.hooks.outputs.env }}" = "prod" ]; then
            echo "Deploying FRONT to PROD..."
            curl -X POST "${{ secrets.RENDER_PROD_HOOK_FRONT }}"
          else
            echo "Deploying FRONT to DEV..."
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONT }}"
          fi
