name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

env:
  imagename: anaskad01/library:${{ github.ref_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.imagename }} .

      - name: Push Docker image
        run: docker push ${{ env.imagename }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: |
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/master' ||
      startsWith(github.ref, 'refs/tags/')

    environment: ${{ 
      github.ref == 'refs/heads/develop' && 'Development' ||
      (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && 'Production'
    }}

    steps:
      - name: Select Render hook based on environment
        id: choose
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "hook_back=${{ secrets.RENDER_DEPLOY_HOOK_BACK }}" >> $GITHUB_OUTPUT
            echo "hook_front=${{ secrets.RENDER_DEPLOY_HOOK_FRONT }}" >> $GITHUB_OUTPUT
          else
            echo "hook_back=${{ secrets.RENDER_PROD_HOOK_BACK }}" >> $GITHUB_OUTPUT
            echo "hook_front=${{ secrets.RENDER_PROD_HOOK_FRONT }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Backend on Render
        run: curl -X POST ${{ steps.choose.outputs.hook_back }}

      - name: Deploy Frontend on Render
        run: curl -X POST ${{ steps.choose.outputs.hook_front }}
